- hosts: gitlab
  environment:
    GITLAB_ROOT_PASSWORD: source_me_from_secret_manager
  become: yes
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: geerlingguy.gitlab
