- hosts: primarydomaincontroller
  roles:
    - role: justin_p.posh5
    - role: justin_p.wincom
    - role: justin_p.pdc
  post_tasks:
    - name: Ensure user bob is present in OU ou=test,dc=domain,dc=local
      community.windows.win_domain_user:
        name: gitlab_ldap_sync
        password: "{{ pswd_gitlab_ldap_sync }}"
        state: present
        path: "ou=Users,dc=domain,dc=test"

- hosts: gitlab
  become: yes
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: robertdebock.gitlab
